INSERT INTO person (name, co, person_id) VALUES ('Stanley Kubrick', 'USA', 1);
INSERT INTO person (name, dob, person_id) VALUES ('Keir Dullea', TO_DATE('30/05/1936', 'DD/MM/YYYY'), 2);
INSERT INTO person (name, email, person_id) VALUES ('Arthur C Clarke', 'arthur@clarke.com', 3);
INSERT INTO person (name, co, email, person_id) VALUES ('George Lucas', 'USA', 'george@email.com', 4);
INSERT INTO person (name, dob, person_id) VALUES ('Mark Hamill', TO_DATE('25/09/1951', 'DD/MM/YYYY'), 5);
INSERT INTO person (name, co, person_id) VALUES ('Robert Mulligan', 'USA', 6);
INSERT INTO person (name, dob, person_id) VALUES ('Gregory Peck', TO_DATE('05/04/1916', 'DD/MM/YYYY'), 7);
INSERT INTO person (name, email, person_id) VALUES ('Harper Lee', 'harper@lee.com', 8);
INSERT INTO person (name, co, email, person_id) VALUES ('James Cameron', 'Canada', 'james@cameron.com', 9);
INSERT INTO person (name, dob, person_id) VALUES ('Leonardo DiCaprio', TO_DATE('11/11/1974', 'DD/MM/YYYY'), 10);
INSERT INTO person (name, co, person_id) VALUES ('David Lean', 'UK', 11);
INSERT INTO person (name, dob, person_id) VALUES ('Julie Christie', TO_DATE('14/04/1940', 'DD/MM/YYYY'), 12);
INSERT INTO person (name, email, person_id) VALUES ('Boris Pasternak', 'boris@boris.com', 13);
INSERT INTO person (name, co, person_id) VALUES ('Anthony Mann', 'USA', 14);
INSERT INTO person (name, dob, person_id) VALUES ('Charlton Heston', TO_DATE('04/10/1923', 'DD/MM/YYYY'), 15);
INSERT INTO person (name, email, person_id) VALUES ('Frederick Frank', 'fred@frank.com', 16);
INSERT INTO person (name, co, email, person_id) VALUES ('Theodoros Angelopoulos', 'Greece', 'theo@angelopoulos.com', 17);
INSERT INTO person (name, dob, person_id) VALUES ('Manos Katrakis', TO_DATE('14/08/1908', 'DD/MM/YYYY'), 18);
INSERT INTO person (name, co, person_id) VALUES ('Paul Verhoeven', 'Netherlands', 19);
INSERT INTO person (name, dob, person_id) VALUES ('Rutger Hauer', TO_DATE('23/01/1944', 'DD/MM/YYYY'), 20);
INSERT INTO person (name, email, person_id) VALUES ('Erik Hazelhoff Roelfzema', 'erik@roelfzema.com', 21);
INSERT INTO person (name, co, email, person_id) VALUES ('Krzysztof Kieslowski', 'Poland', 'email@email.com', 22);
INSERT INTO person (name, dob, person_id) VALUES ('Juliette Binoche', TO_DATE('09/03/1964', 'DD/MM/YYYY'), 23);
INSERT INTO person (name, co, person_id) VALUES ('Jean-Paul Rappeneau', 'France', 24);
INSERT INTO person (name, dob, person_id) VALUES ('Gerard Depardieu', TO_DATE('27/12/1948', 'DD/MM/YYYY'), 25);
INSERT INTO person (name, email, person_id) VALUES ('Edmond Rostand', 'edmond@rostand.com', 26);