INSERT INTO film (film_id, title, release_year, genre, score, director_id, writer_id) VALUES (1, '2001: A Space Odyssey', 1968, 'Science Fiction', 10, 1, 1);
INSERT INTO film (film_id, title, release_year, genre, score, director_id, writer_id) VALUES (2, 'Star Wars: A New Hope', 1977, 'Science Fiction', 7, 2, 2);
INSERT INTO film (film_id, title, release_year, genre, score, director_id, writer_id) VALUES (3, 'To Kill A Mockingbird', 1962, 'Drama', 10, 3, 3);
INSERT INTO film (film_id, title, release_year, genre, score, director_id, writer_id) VALUES (4, 'Titanic', 1997, 'Romance', 5, 4, 4);
INSERT INTO film (film_id, title, release_year, genre, score, director_id, writer_id) VALUES (5, 'Dr Zhivago', 1965, 'Historical', 8, 5, 5);
INSERT INTO film (film_id, title, release_year, genre, score, director_id, writer_id) VALUES (6, 'El Cid', 1961, 'Historical', 6, 6, 6);
INSERT INTO film (film_id, title, release_year, genre, score, director_id, writer_id) VALUES (7, 'Voyage to Cythera', 1984, 'Drama', 8, 7, 7);
INSERT INTO film (film_id, title, release_year, genre, score, director_id, writer_id) VALUES (8, 'Soldier of Orange', 1977, 'Thriller', 8, 8, 8);
INSERT INTO film (film_id, title, release_year, genre, score, director_id, writer_id) VALUES (9, 'Three Colours: Blue', 1993, 'Drama', 8, 9, 9);
INSERT INTO film (film_id, title, release_year, genre, score, director_id, writer_id) VALUES (10, 'Cyrano de Bergerac', 1990, 'Historical', 9, 10, 10);